wandb_version: 1

BatchNormalization_momentum:
  desc: null
  value: 0.999
BiLstm_units:
  desc: null
  value: 21
Conv1D_strides:
  desc: null
  value: 40
Conv1D_units:
  desc: null
  value: 31
MaxPooling1D_strides:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1671876425.589202
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 23
      - 37
      4: 3.7.13
      5: 0.13.5
      8:
      - 3
      - 5
      10:
      - 3
      - 9
dropout:
  desc: null
  value: 0.1
