wandb_version: 1

BiLstm_units:
  desc: null
  value: 21
Conv1D_activation:
  desc: null
  value: relu
Conv1D_filters:
  desc: null
  value: 31
Conv1D_strides:
  desc: null
  value: 30
_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1677251187.052016
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 16
      - 23
      - 37
      4: 3.7.13
      5: 0.13.10
      8:
      - 3
      - 5
      10:
      - 9
dropout:
  desc: null
  value: 0.4
